#!/usr/bin/env bash
hax() {
    text="$1"
    for (( i=0; i<${#text}; i++ ));do
        char="${text:$i:1}"
        printf "$char"
        sleep 0.06
    done
    printf "\n"

    [ $2 ] && wait=$2 || wait=1
    sleep $wait
}
hax "Agent 49"
hax "Install ArchLinux on Time."
hax "Your Target is waiting."
